admin_event_category:
  path: /
  defaults: {_controller: ProjectBundle:AdminEventCategory:index}
  requirements:
    _method: get

admin_event_category_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminEventCategory:new}

admin_event_category_create:
  path: /create
  defaults: {_controller: ProjectBundle:AdminEventCategory:create}
  requirements:
    _method: post

admin_event_category_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminEventCategory:edit}
  requirements:
    id: \d+

admin_event_category_update:
  path: /{id}
  defaults: {_controller: ProjectBundle:AdminEventCategory:update}
  requirements:
    _method: post
    id: \d+

admin_event_category_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminEventCategory:delete}
  requirements:
    _method: get

admin_event_category_group_delete:
  path: /group-delete
  defaults: {_controller: ProjectBundle:AdminEventCategory:group_delete}
  requirements:
    _method: post

admin_event_category_sort:
  path: /sort
  defaults: {_controller: ProjectBundle:AdminEventCategory:sort}
  requirements:
    _method: get

admin_event_category_sort_prosess:
  path: /sort-prosess
  defaults: {_controller: ProjectBundle:AdminEventCategory:sort_prosess}
  requirements:
    _method: post
