admin_our_client:
  path: /
  defaults: {_controller: ProjectBundle:AdminOurClient:index}
  requirements:
    _method: get

admin_our_client_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminOurClient:new}

admin_our_client_create:
  path: /create
  defaults: {_controller: ProjectBundle:AdminOurClient:create}
  requirements:
    _method: post

admin_our_client_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminOurClient:edit}
  requirements:
    id: \d+

admin_our_client_update:
  path: /{id}
  defaults: {_controller: ProjectBundle:AdminOurClient:update}
  requirements:
    _method: post
    id: \d+

admin_our_client_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminOurClient:delete}
  requirements:
    _method: get

admin_our_client_group_delete:
  path: /group-delete
  defaults: {_controller: ProjectBundle:AdminOurClient:group_delete}
  requirements:
    _method: post

admin_our_client_group_enable:
  path: /group-enable
  defaults: {_controller: ProjectBundle:AdminOurClient:group_enable}
  requirements:
    _method: post

admin_our_client_group_disable:
  path: /group-disable
  defaults: {_controller: ProjectBundle:AdminOurClient:group_disable}
  requirements:
    _method: post

admin_our_client_sort:
  path: /sort
  defaults: {_controller: ProjectBundle:AdminOurClient:sort}
  requirements:
    _method: get

admin_our_client_sort_prosess:
  path: /sort-prosess
  defaults: {_controller: ProjectBundle:AdminOurClient:sort_prosess}
  requirements:
    _method: post
