admin_product_category:
  path: /
  defaults: {_controller: ProjectBundle:AdminProductCategory:index}
  requirements:
    _method: get

admin_product_category_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminProductCategory:new}

admin_product_category_create:
  path: /create
  defaults: {_controller: ProjectBundle:AdminProductCategory:create}
  requirements:
    _method: post

admin_product_category_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminProductCategory:edit}
  requirements:
    id: \d+

admin_product_category_update:
  path: /{id}
  defaults: {_controller: ProjectBundle:AdminProductCategory:update}
  requirements:
    _method: post
    id: \d+

admin_product_category_move_position:
  path: /{id}/move
  defaults: {_controller: ProjectBundle:AdminProductCategory:move_position}
  requirements:
    id: \d+

admin_product_category_move_position_update:
  path: /{id}/move_update
  defaults: {_controller: ProjectBundle:AdminProductCategory:move_position_update}
  requirements:
    _method: post
    id: \d+

admin_product_category_move_up_position:
  path: /{id}/move/up
  defaults: {_controller: ProjectBundle:AdminProductCategory:move_up_position}
  requirements:
    id: \d+

admin_product_category_move_down_position:
  path: /{id}/move/down
  defaults: {_controller: ProjectBundle:AdminProductCategory:move_down_position}
  requirements:
    id: \d+

admin_product_category_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminProductCategory:delete}
  requirements:
    _method: get
