<?php

namespace ProjectBundle\Repository;

/**
 * AuthenticationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthenticationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getGroupData()
	{
		$qb = $this->createQueryBuilder('a');
		$qb->groupBy('a.groupType');
		return $qb;
	}

	public function getDataByGroup($group_type)
	{
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.groupType = :group_type')
				->setParameter('group_type', $group_type);
		return $qb;
	}
}
