<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;


/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
    public function findAllData($arr_query_data=false)
    {
        $qb = $this->createQueryBuilder('b');
		//join translation
		$qb->leftJoin('b.translations', 'bt')
				->select('b', 'bt')
				->orderBy('b.position', 'ASC')
                ->addOrderBy('b.publicDate', 'DESC')
				->addOrderBy('b.createdAt', 'DESC');

		$q = $arr_query_data['q'];
  		if($q){
			//search from translation
  			$qb->andWhere($qb->expr()->orX(
	  	      	$qb->expr()->like('bt.title', ':query'),
	  			$qb->expr()->like('bt.subtitle', ':query')
			))
  			->setParameter('query', '%'.$q.'%');
  		}

  		return $qb;
    }

    public function findAllActiveData($locale='en')
    {
        $qb = $this->findAllData();
        $qb->andWhere($qb->expr()->andX(
                $qb->expr()->like('b.status', ':status'),
                $qb->expr()->lte('b.publicDate', ':publicdate')
        		// $qb->expr()->like('bt.locale', ':locale')
            ))
            ->setParameters(array(
                'status' => 1,
                'publicdate' => date('Y-m-d')
        		// 'locale' => $locale
            ))
        ;
        return $qb;
    }

}
