<?php

namespace ProjectBundle\Repository;

/**
 * BlogImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogImageRepository extends \Doctrine\ORM\EntityRepository
{
}
