<?php

namespace ProjectBundle\Repository;

/**
 * CountryCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryCodeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllData($arr_query_data=false)
	{
        $qb = $this->createQueryBuilder('c');
		$qb->orderBy('c.position', 'ASC');

		if(isset($arr_query_data['q'])){
			$q = $arr_query_data['q'];
			$qb->where($qb->expr()->orX(
				$qb->expr()->like('c.country', ':query')
			))
			->setParameter('query', '%'.$q.'%');
		}
		return $qb;
	}
}
