<?php

namespace ProjectBundle\Repository;
use Symfony\Component\Intl\Locale;

/**
 * CustomerOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findItemBestSeller($locale=false){
        $locale = ($locale) ? $locale : Locale::getDefault();
        $qb = $this->createQueryBuilder('coi')
        ->select('count(coi.product) as itemCount,p.id as productId,pdt.title,p.price,p.compareAtPrice,p.image')
            ->innerJoin('coi.product','p')
            ->innerJoin('p.translations', 'pdt')
            ->Where('p.status = :status and pdt.locale = :locale')
            ->groupBy('coi.product,pdt.id,pdt.title')
            ->orderBy('itemCount','DESC')
                ->setParameter('status',1)
                ->setParameter('locale',$locale);
        return $qb;
    }
}
