<?php

namespace ProjectBundle\Repository;

/**
 * CustomerGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerGroupRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllData($arr_query_data=false)
	{
		//QueryBuilder Expr
		$qb = $this->createQueryBuilder('c');
		//join translation
		$qb->join('c.translations', 'ct')
				->select('c', 'ct')
				->orderBy('c.position', 'ASC')
				->addOrderBy('c.createdAt', 'DESC');

		$q = $arr_query_data['q'];
		if($q){
			//search from translation
			$qb->where($qb->expr()->orX(
				$qb->expr()->like('ct.title', ':query')
			))
			->setParameter('query', '%'.$q.'%');
		}
		return $qb;
	}


	public function getCustomerGroupByProduct($product, $locale)
	{
		$query = $this->getEntityManager()
			->createQuery(
				'SELECT cg, cgt  FROM ProjectBundle:CustomerGroup cg
				JOIN cg.products p
				LEFT JOIN cg.translations cgt
				WHERE p.status = :status
					AND p.id = :product_id
					AND cgt.locale = :locale'
			)->setParameters(array(
				'status'=>1,
				'product_id'=>$product->getId(),
				'locale'=>$locale
			));
			// ORDER BY a.position asc, a.createdAt desc'

		return $query->getResult();
		// return $query->getArrayResult();
	}


}
