<?php

namespace ProjectBundle\Repository;

/**
 * DeliveryMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
