<?php

namespace ProjectBundle\Repository;

/**
 * DiscountSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountSettingRepository extends \Doctrine\ORM\EntityRepository
{
	public function getOneData()
	{
		return $this->createQueryBuilder('d')
			->getQuery()
			->getOneOrNullResult();
	}
}
