<?php

namespace ProjectBundle\Repository;

/**
 * MuscleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuscleRepository extends \Doctrine\ORM\EntityRepository
{
		public function findAllData($arr_query_data=false)
		{
			//QueryBuilder Expr
			$qb = $this->createQueryBuilder('m');
			//join translation
			$qb->join('m.translations', 'mt')
					->select('m', 'mt')
					->orderBy('m.position', 'ASC')
					->addOrderBy('m.createdAt', 'DESC');

			$q = $arr_query_data['q'];
			if($q){
				//search from translation
				$qb->where($qb->expr()->orX(
					$qb->expr()->like('mt.title', ':query')
				))
				->setParameter('query', '%'.$q.'%');
			}
			return $qb;
		}

		public function getMuscleByProduct($product, $locale)
		{
			$query = $this->getEntityManager()
				->createQuery(
					'SELECT mu, mut  FROM ProjectBundle:Muscle mu
					JOIN mu.products p
					LEFT JOIN mu.translations mut
					WHERE p.status = :status
						AND p.id = :product_id
						AND mut.locale = :locale'

				)->setParameters(array(
					'status'=>1,
					'product_id'=>$product->getId(),
					'locale'=>$locale
				));
				// ORDER BY a.position asc, a.createdAt desc'

			return $query->getResult();
			// return $query->getArrayResult();
		}
}
