<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * OurClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OurClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllData($arr_query_data=false)
    {
        $qb = $this->createQueryBuilder('o');
		//join translation
		$qb->join('o.translations', 'ot')
				->select('o', 'ot')
				->orderBy('o.position', 'ASC')
				->addOrderBy('o.createdAt', 'DESC');

		$q = $arr_query_data['q'];
  		if($q){
			//search from translation
  			$qb->andWhere($qb->expr()->orX(
	  	      	$qb->expr()->like('ot.title', ':query')
			))
  			->setParameter('query', '%'.$q.'%');
  		}

  		return $qb;
    }

    public function findAllActiveData($locale='en')
    {
        $qb = $this->findAllData();
        $qb->andWhere($qb->expr()->andX(
                $qb->expr()->like('o.status', ':status'),
        		$qb->expr()->like('ot.locale', ':locale')
            ))
            ->setParameters(array(
                'status' => 1,
        		'locale' => $locale
            ))
        ;
        return $qb;
    }
}
