<?php

namespace ProjectBundle\Repository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllData($arr_query_data=false)
  	{
		$qb = $this->createQueryBuilder('p')->orderBy('p.createdAt', 'DESC');
		return $qb;
	}

	public function getActiveDataByName($name,$locale='en')
	{
		$qb = $this->createQueryBuilder('p');
		$qb	->select('p','pt')
			->leftjoin('p.translations', 'pt')
			->andWhere($qb->expr()->andX(
	        	$qb->expr()->like('p.status', ':status'),
				$qb->expr()->like('p.name', ':name'),
				$qb->expr()->like('pt.locale', ':locale')
	        ))
			->setParameters(array(
                'status' => 1,
				'name' => $name,
				'locale' => $locale
            ))
		;
		try {
            return $qb->getQuery()->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
	}
}
