<?php

namespace ProjectBundle\Repository;

/**
 * PaymentBankTransferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentBankTransferRepository extends \Doctrine\ORM\EntityRepository
{
}
