<?php

namespace ProjectBundle\Repository;

/**
 * PortfolioImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioImageRepository extends \Doctrine\ORM\EntityRepository
{
}
