<?php

namespace ProjectBundle\Repository;

/**
 * PortfolioTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
