<?php

namespace ProjectBundle\Repository;

/**
 * PowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PowerRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAllData($arr_query_data=false)
	{
			//QueryBuilder Expr
			$qb = $this->createQueryBuilder('p');
			//join translation
			$qb->join('p.translations', 'pt')
					->select('p', 'pt')
					->orderBy('p.position', 'ASC')
					->addOrderBy('p.createdAt', 'DESC');

			$q = $arr_query_data['q'];
			if($q){
				//search from translation
				$qb->where($qb->expr()->orX(
					$qb->expr()->like('pt.title', ':query'),
					$qb->expr()->like('pt.description', ':query')
				))
				->setParameter('query', '%'.$q.'%');
			}

			return $qb;
	}
}
