<?php

namespace ProjectBundle\Repository;

/**
 * PromotionDownloadCounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionDownloadCounterRepository extends \Doctrine\ORM\EntityRepository
{
}
