<?php

namespace ProjectBundle\Repository;

/**
 * RequestServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllData($arr_query_data=false)
    {
        //QueryBuilder Expr
        $qb = $this->createQueryBuilder('rs')
        // $qb->where($qb->expr()->andX(
        //     $qb->expr()->like('u.roles', ':user_roles')
        // ))
        ->orderBy('rs.createdAt', 'DESC');

        $q = $arr_query_data['q'];
        if($q){
            $qb->andWhere($qb->expr()->orX(
                $qb->expr()->like('rs.firstName', ':query'),
                $qb->expr()->like('rs.lastName', ':query'),
                $qb->expr()->like('rs.phone', ':query'),
                $qb->expr()->like('rs.productTitle', ':query'),
                $qb->expr()->like('rs.productModel', ':query'),
                $qb->expr()->like('rs.productSerialNumber', ':query'),
                $qb->expr()->like('rs.email', ':query'),
                $qb->expr()->like("CONCAT(rs.firstName, ' ', rs.lastName)", ':query')
            ))
            ->setParameter('query', '%'.$q.'%');
        }
        return $qb;
    }
    public function countBy(array $criteria)
  {
      $persister = $this->_em->getUnitOfWork()->getEntityPersister($this->_entityName);
      return $persister->count($criteria);
  }
}
