<?php

namespace ProjectBundle\Repository;

/**
 * SettingOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingOptionRepository extends \Doctrine\ORM\EntityRepository
{

	public function getDataByCatType($cat_type)
	{
		//QueryBuilder
		$qb = $this->createQueryBuilder('s');
		$qb->where('s.catType = :cat_type')
		    ->setParameter('cat_type', $cat_type)
		    ->groupBy('s.groupType')
			->orderBy('s.id', 'ASC');

		return $qb;
	}

	public function getDataByGroup($cat_type, $group_type)
	{
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.catType = :cat_type')
			->andWhere('a.groupType = :group_type')
			->setParameter('cat_type', $cat_type)
			->setParameter('group_type', $group_type);
		return $qb;
	}
}
