<?php

namespace ProjectBundle\Repository;

/**
 * ShippingRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingRateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllData($arr_query_data=false)
    {
        $qb = $this->createQueryBuilder('sr')
                ->OrderBy('sr.createdAt', 'DESC');
        $q = $arr_query_data['q'];
        if($q){
            $qb->where($qb->expr()->orX(
                $qb->expr()->like('sr.title', ':query')
            ))
            ->setParameter('query', '%'.$q.'%');
        }
        return $qb;
    }
}
