<?php

namespace ProjectBundle\Repository;

/**
 * SkuValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkuValueRepository extends \Doctrine\ORM\EntityRepository
{
		public function findAllDataBySku($sku)
		{
			//QueryBuilder Expr
			$qb = $this->createQueryBuilder('sv');
			$qb->select('sv', 'v', 'vo')
					->where('sv.sku = :sku')
					->setParameter('sku', $sku)
					->leftjoin('sv.variant', 'v')
					->leftjoin('sv.variantOption', 'vo');
			return $qb;
		}
}
