<?php

namespace ProjectBundle\Repository;

/**
 * StyleCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StyleCategoryRepository extends \Doctrine\ORM\EntityRepository
{
		public function findAllData($arr_query_data=false)
		{
			//QueryBuilder Expr
			$qb = $this->createQueryBuilder('b');
			$qb->orderBy('b.position', 'ASC')
				->addOrderBy('b.createdAt', 'DESC');
			$q = $arr_query_data['q'];
			if($q){
				$qb->where($qb->expr()->orX(
					$qb->expr()->like('b.title', ':query'),
					$qb->expr()->like('b.description', ':query')
				))
				->setParameter('query', '%'.$q.'%');
			}
			return $qb;
		}

		public function getDataWithStyle()
	  {
			return $this->findAllData()
						->leftjoin('b.styles', 's')
						->where('s.status = 1')
						->groupBy('b.id')
						;
	  }

}
