<?php

namespace ProjectBundle\Repository;

/**
 * TemplateCustomerGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateCustomerGroupRepository extends \Doctrine\ORM\EntityRepository
{
	private $qb;

	public function findAllData($arr_query_data=false)
	{
		//QueryBuilder
		$this->qb = $this->createQueryBuilder('c');
		//join translation
		$this->qb->join('c.translations', 'ct')
				->select('c', 'ct')
				->orderBy('c.position', 'ASC')
				->addOrderBy('c.createdAt', 'DESC');

		$q = $arr_query_data['q'];
		if($q){
			//search from translation
			$this->qb->where($this->qb->expr()->orX(
				$this->qb->expr()->like('ct.title', ':query')
			))
			->setParameter('query', '%'.$q.'%');
		}
		return $this->qb;
	}

	public function findAllDataJoinedCustomerGroup($arr_query_data=false)
	{
		$this->findAllData($arr_query_data);

		$this->qb->addSelect('cg', 'cgt');
		$this->qb->innerJoin('c.customerGroup', 'cg')
			->leftjoin('cg.translations', 'cgt');

		return $this->qb;
	}


}
