<?php

namespace ProjectBundle\Repository;

/**
 * VariantOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariantOptionRepository extends \Doctrine\ORM\EntityRepository
{
		public function findNameByVariant($variant, $option_value)
		{
			return $this->findOneBy(
				array('variant' => $variant, 'name' => $option_value)
			);
		}
}
