<?php

namespace ProjectBundle\Repository;

/**
 * VariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariantRepository extends \Doctrine\ORM\EntityRepository
{
		public function findNameByProduct($product, $option_name)
		{
			return $this->findOneBy(
				array('product' => $product, 'name' => $option_name)
			);
		}
}
